name: PlaytimesX
version: "1.0"
main: me.ajan12.PlaytimesX.PlaytimesX
author: ajan_12

commands:
  playtimesx:
    usage: /playtimesx <reload|recalculate-rankup|next-rankup> OR /playtimesx <display-profiles> [page] OR /playtimesx <display-profile> [player]
  playtime:
    aliases: pi, pinfo, playerinfo, pt, ptime
    usage: /playtime [player]
  ranks:
    aliases: ri, rinfo, rankinfo
    usage: /ranks
  plus:
    usage: /plus [player]

permissions:
  playtimesx.command.main:
    description: The permission node to use command /playtimesx.
    default: op
  playtimesx.command.plus:
    description: The permission to use command /plus.
    default: op
  playtimesx.*:
    description: Gives access to all commands.
    default: false
    children:
      playtimesx.command.main: true
      playtimesx.command.plus: true